---
# tasks file for create-ami
- name: Create AMI
  ec2_ami:
    region: "{{ ami.region }}"
    instance_id: "{{ ec2_id }}"
    name: "{{ami.name}}"
    wait: yes
    state: present
  register: new_ami

- name: Set new AMI ID as fact
  set_fact: new_ami_id="{{ new_ami.image_id }}"
